import re


FORBIDDEN_KEYWORDS = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "ALTER",
    "TRUNCATE",
    "CREATE",
    "RENAME",
]


def validate_sql(sql):
    """
    Clean and validate SQL generated by the LLM.
    """

    if not sql:
        return False, "SQL query is empty."

    # Remove leading/trailing whitespace
    sql = sql.strip()

    # Remove Markdown code fences
    sql = re.sub(
        r"^```(?:sql)?\s*",
        "",
        sql,
        flags=re.IGNORECASE
    )

    sql = re.sub(
        r"\s*```$",
        "",
        sql
    )

    sql = sql.strip()

    sql_upper = sql.upper()

    # Only SELECT queries are allowed
    if not sql_upper.startswith("SELECT"):
        return False, "Only SELECT queries are allowed."

    # Block dangerous SQL commands
    for keyword in FORBIDDEN_KEYWORDS:

        pattern = rf"\b{keyword}\b"

        if re.search(pattern, sql_upper):
            return False, (
                f"Forbidden SQL keyword detected: {keyword}"
            )

    return True, sql